### ISSUE TITLE
Rule and archetype for DSM 5 Guideline 

### ISSUE THREAD

**Issue by MaryamRazavi** [gdl-lang/common-clinical-models#421]
GDL 2 editor
in this guideline there are symptoms for depression diagnosis.
I think for the required symtoms I can have Boolean elements in the archetype and for others I can have ordinal elements. 
required criteria ( ≥5 depressive symptoms above, depressed mood and/or loss of interest/pleasure must be present) plus  all 4 Additional required criteria Must be present. 
The question is how I can rule this inGDL2 editor? since I need to have a function like AND function. 
link to the guideline: https://www.mdcalc.com/dsm-5-criteria-major-depressive-disorder

**Comment by winnerng** [comment]
I would suggest you quantify the answer instead. Rather than using "pure" Boolean, You can use Ordinal type element, and set the answer value to (1-Yes) and (0-No) for all the criteria. Then you can group the criteria and create a "subtotal score" count element for each group. Use the following subtotal score to set the rule. 
For example, first, you can create the ordinal element to represent all the criteria in both groups, the depressive symptoms group, and the additional required criteria group. Then, you create two count elements "depressive symptom subtotal" and "additional required criteria subtotal". For each, you set the rule to sum the value for each of them based on the criteria underneath them. After that, you can set rule(s) for the interpretation, such as if "depressive symptom subtotal" <5 or "additional required criteria subtotal" <4 then diagnostic result = negative, while if "depressive symptom subtotal" ≥ 5 and "additional required criteria subtotal"== 4 then diagnostic result = positive and other rules as necessary. 

I've used this kind of approach several times, maybe someone has another idea as well.

**Comment by MaryamRazavi** [comment]
Thank you for responding. I also thought of that but the problem is two elements are required. As I remember base on Isabelle comment there is no function on GDL2 editor to define a question as required. This solution is working for all part except when I must have positive answer for first two question to get the correct result. Any suggestion for that?

**Comment by KalliamvakosKon** [comment]
@MaryamRazavi the solution is very similar to what @winnerng proposed. I would use the following approach.

For the archetype:
* All questions should be ordinals with 1-Yes and 0-No regardless if mandatory or not.
* You will need a subtotal for the Depressive symptoms
* You will need a subtotal for the Additional required criteria

For the guideline:
* Add a default action for Diagnostic result = Not positive
* Create two rules to calculate the subtotals for each group
* Create a rule that would check when a patient is Positive:
  * Depressed mood = Yes
  * Loss of interest = Yes
  * Depressive symptoms subtotal >= 5
  * Additional required criteria subtotal = 4

If any of the above criteria is not met the guideline will circle back to the default action.
