### ISSUE TITLE
ASTRAL guideline doesn't  execute for number less than 10 for NIHSS score! 

### ISSUE THREAD

**Issue by MaryamRazavi** [gdl-lang/common-clinical-models#422]
This guideline doesn't  execute for number less than 10 for NIHSS score! 
GDL2 Editor 
Steps to reproduce issue: 

* upload the archetype and the guideline
* for NIHSS score you need to have a number less than 10, in this way the guideline will not execute. 

[ASTRAL_Score_for_Ischemic_Stroke_guideline.v0.gdl2.zip](https://github.com/gdl-lang/common-clinical-models/files/4369892/ASTRAL_Score_for_Ischemic_Stroke_guideline.v0.gdl2.zip)

**Comment by KalliamvakosKon** [comment]
@MaryamRazavi the zip you attached in the issue did't contain all the necessary archetypes to be able to open this on GDL2 Editor.

However I managed to find them and look into the guideline.

This appears to be a bug in the GDL2 Editor with DV_COUNT elements that are single digit.

To circumvent this issue until is fixed when you want to use a single digit value for NHISS add a 0 in front of it. E.g. 01 instead of 1.

Also, your Astral Score element should be of type COUNT and not quantity since this score is only going to contain integers.

If this solves your issue please go ahead and close the issue :)
