### ISSUE TITLE
Cannot define a rule with OR Function

### ISSUE THREAD

**Issue by winnerng** [gdl-lang/common-clinical-models#495]
Hi team,
I encountered an issue where I can't define a rule condition using the OR function.
![Annotation 2020-06-16 091819](https://user-images.githubusercontent.com/49078821/84744415-8397ec80-afb3-11ea-819d-fbee7d56c438.png)
![Annotation 2020-06-15 231411](https://user-images.githubusercontent.com/49078821/84744418-84308300-afb3-11ea-86b4-8a993cde1615.png)
I tried using other elements and still got the same error message. Any suggestions?
If it's not possible to use the OR function for now then I think I'll use the ordinal element instead of fetching the input from existing archetypes.

**Comment by KalliamvakosKon** [comment]
@winnerng for which app is this so that I can try to replicate?

Also does this error come up when you try to use the "Execute tab"? If yes, I find that quite often that tab is bugged, but then if you use a fixture text in the "Test" tab everything works fine.

**Comment by winnerng** [comment]
It's in the new guideline model I am working with, the Newsom score. I've just created a pull request so that you can get the files. And the error message also showed up when I saved the guideline thus the rule did not appear in when I open it using Notepad++ as well.

**Comment by Hemiho** [comment]
![image](https://user-images.githubusercontent.com/66406227/84993741-f63ad080-b149-11ea-9a9a-03f4e04b7412.png)
![image](https://user-images.githubusercontent.com/66406227/84993767-018dfc00-b14a-11ea-998a-dec9522ead61.png)
I think I have the same issue

**Comment by KalliamvakosKon** [comment]
@winnerng there is a bug currently in GDL2 (not just the editor) with temperature units because of the degrees special character ''°".

A way to circumvent this problem is to check for the magnitude and the unit like this:

![Capture](https://user-images.githubusercontent.com/19977620/85021189-cdc6cc80-b171-11ea-9f8d-8f5a3aa24eb1.PNG)

This way you get to wrap the °C or °F in single quotes and it's parsed as string.

@Hemiho I don't think you have the same problem because your units don't have a special character. I will need to look into your individual case, so please upload your models (if not done already) so that I can take a look.

**Comment by winnerng** [comment]
Mine is fixed after applying Kostas' suggestion. Thanks
